library(shiny)
library(tidyverse)
library(readxl)
library(DT)
library(patchwork)
library(gridExtra)

source("R/helpers.R")
source("R/data_processing.R")
source("R/uniformity_plots.R")
source("R/parallelism_tables.R")
source("R/ruggedness_tables.R")